### ISSUE TITLE
Semana 2: Documentación: aspectos relevantes / Conceptos teóricos/ planificación temporal

### ISSUE THREAD

**Issue by Itg0001** [Itg0001/TFG_DietaPorDientes#10]
Esta semana lo primordial a hacer va a ser actualizar la documentación explicando y comentando las funciones y la parte que vamos a usar una vez terminado el prototipo de la herramienta que aun podría estar sujeta a futuras modificaciones por parte de lo establecido hasta el momento.

**Comment by Itg0001** [comment]
++[SOLUCIONADO]

Estoy teniendo problemas con las imágenes en la memoria hay una de ejemplo pero esta en formato .pdf y las capturas que estoy usando están en formato .png por lo tanto ¿solo valen las imágenes en formato .pdf ?de ser así como podría transformarlas ya que cambiando la extensión el archivo se queda corrupto

**Comment by alvarag** [comment]
Son válidos múltiples formatos de imágenes. PDF es más recomendable por su calidad, pero PNG también puedes utilizarlo

**Comment by alvarag** [comment]
Para incluir pseudocódigos:
\usepackage[linesnumbered,ruled,vlined,spanish]{algorithm2e}

Ejemplos:

%LSH_IS_S
\begin{algorithm*}
\DontPrintSemicolon
\KwIn{A training set $ X = \lbrace(\mathbf{x}_{1},y_{1}),...,(\mathbf{x}_{n},y_{n})\rbrace$,
      set $\mathcal{G}$ of hash function families}
\KwOut{The set of selected instances $ S \subseteq X $ }

$ S = \varnothing $

\ForEach {instance $ \mathbf{x} \in X $} {
  \ForEach {function family $g \in\mathcal{G} $} {
     $u\leftarrow$ bucket assigned to $\mathbf{x}$ by family $g$ \;
     \If {there is no other instance of the same class of $\mathbf{x}$ in $u$}
     {
       Add $ \mathbf{x} $ to $ S $ \;
       Add $ \mathbf{x} $ to $ u $ \;
     }
  }
}

\Return {$S$}
\caption{LSH-IS-S -- Instance selection algorithm by hashing \repAAG{in one pass}{\emph{stream} processing}.}
\label{alg:LSH-S}
\end{algorithm*}

%LSH_IS_F
\begin{algorithm*}
\DontPrintSemicolon
\KwIn{A training set $ X = \lbrace(\mathbf{x}_{1},y_{1}),...,(\mathbf{x}_{n},y_{n})\rbrace$,
      set $\mathcal{G}$ of hash function families}
\KwOut{The set of selected instances $ S \subseteq X $ }

$ S = \varnothing $

\ForEach {instance $ \mathbf{x} \in X $} {
  \ForEach {function family $g \in\mathcal{G} $} {
     $u \leftarrow $ bucket assigned to $\mathbf{x}$ by family $g$ \;
     Add $ \mathbf{x} $ to $ u $ \;
  }
}

\ForEach {function family $g \in \mathcal{G} $} {
  \ForEach {bucket $u$ of $g$} {
     \ForEach {class $y$ with some instance in $ u $} {
       $ I_y \leftarrow $ all instances of class $y$ in $u$\;
       \If {$ |I_y| > 1 $} 
       {
         Add to $S$ one random instance of $ I_y $ \;
       }
     }
  }
}

\Return {$S$}
\caption{LSH-IS-F -- Instance selection algorithm by hashing with two passes.}
\label{alg:LSH-F}
\end{algorithm*}

**Comment by alvarag** [comment]
Para más de una figura utilizar  paquete subcaption (http://texdoc.net/texmf-dist/doc/latex/caption/subcaption.pdf)

\begin{figure}
\begin{subfigure}[b]{.5\linewidth}
\centering\large A
\caption{A subfigure}\label{fig:1a}
\end{subfigure}%
\begin{subfigure}[b]{.5\linewidth}
\centering\large B
\caption{Another subfigure}\label{fig:1b}
\end{subfigure}
\caption{A figure}\label{fig:1}
\end{figure}
