### ISSUE TITLE
Semana 6

### ISSUE THREAD

**Issue by alvarag** [Itg0001/TFG_DietaPorDientes#27]
Tareas para el 6º sprint del proyecto. El objetivo es tener una primera versión del  entregable para poder empezar a probar cosas "más sofisticadas" ;)
- [x] Completar los menús de la GUI 
- [x] Completar la documentación de los fuentes Python
- [x] Pruebas unitarias

Enlaces de interés para las pruebas:
- http://docs.python-guide.org/en/latest/writing/tests/
- http://www.onlamp.com/pub/a/python/2004/12/02/tdd_pyunit.html
- https://docs.python.org/2/library/unittest.html

**Comment by Itg0001** [comment]
Esta semana algún gráfico quedara algo descuadrado ya que el viernes por la tarde de la semana 5 no pude cerrar las tareas por el ataque a Dyn entre ellos GitHub dejo de funcionar y hasta el sábado no pude cerrar las tareas y abrir las de la semana 6.
Adjunto enlace de la noticia: "http://www.elmundo.es/tecnologia/2016/10/22/580b10e5268e3e06158b45e0.html"
