### ISSUE TITLE
Semana 7: Corregir memorias.

### ISSUE THREAD

**Issue by Itg0001** [Itg0001/TFG_DietaPorDientes#35]
Esta semana vamos a revisar la corrección de las memorias y plasmar los cambios.
- [x]  Corregir memorias.

**Comment by alvarag** [comment]
Veo que la versión de la memoria es de hace 7 días, ¿es esa la que debo revisar? Confírmamelo para poder echarle un ojo en los "ratos muertos".

**Comment by Itg0001** [comment]
Buenos días, no había visto el correo hasta ahora, te confirmo que si que es esa versión.

**Comment by alvarag** [comment]
Adjunto documentación comentada
[memoriaC.pdf](https://github.com/Itg0001/TFG_DietaPorDientes/files/568474/memoriaC.pdf)
[anexosC.pdf](https://github.com/Itg0001/TFG_DietaPorDientes/files/568475/anexosC.pdf)
