### ISSUE TITLE
Semana 8: Investigar sobre algoritmos de procesado.

### ISSUE THREAD

**Issue by Itg0001** [Itg0001/TFG_DietaPorDientes#41]
Esta semana va a consistir en investigar:
- [x]  Investigar sobre algoritmos de deteccion de bordes por procesado de imágenes.

**Comment by joseFranciscoDiez** [comment]
- [x] Primero de todo mejorar la imagen mediante equalización
  http://scikit-image.org/docs/dev/auto_examples/plot_equalize.html
- [x] Probar máscaras personalizadas para poder hacer Kirsch https://en.wikipedia.org/wiki/Kirsch_operator
  Usando Convolve https://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.ndimage.filters.convolve.html
- [x] Probar substracción del fondo
  http://scikit-image.org/docs/dev/auto_examples/plot_regional_maxima.html

**Comment by joseFranciscoDiez** [comment]
Buscar
Dental Microwear y texture analysis para identificar técnicas que usan en este campo. 
Parece que se olvidan de analizar como son las líneas, es otro enfoque distinto del nuestro, pero nos puede dar ideas.
