### ISSUE TITLE
Semana 9: Ejecutable sin dependecias

### ISSUE THREAD

**Issue by joseFranciscoDiez** [Itg0001/TFG_DietaPorDientes#42]
Despues de intentar probar sin éxito la aplicación debido a que mi versión de Anaconda no era la más reciente he visto la necesidad de poder hacer un ejecutable sin dependencias.

No se debería pedir a un usuario que se instale todo Anaconda solo para poder ejecutar una aplicación en python, igual que no se le pide a un usuario instalar Visual Studio para ejecutar una aplicación en C++.

Existen una serie de herramientas para poder distribuir aplicaciones python sin necesidad de dependencias:
- py2exe 
- py2app
- pyinstaller
- cx_Freeze

Se debería evaluar la posibilidad de usarlas.

**Comment by joseFranciscoDiez** [comment]
Freezing Your Code http://docs.python-guide.org/en/latest/shipping/freezing/

**Comment by joseFranciscoDiez** [comment]
https://cx-freeze.readthedocs.io/en/latest/releasenotes.html

**Comment by joseFranciscoDiez** [comment]
Otra opción crear un paquete distribuible https://packaging.python.org/distributing/#packaging-your-project

**Comment by joseFranciscoDiez** [comment]
Si continuamos con pyinstaller.
Un problema es que las últimas veces no le hemos dicho que la aplicación era "windowed".

Otro problema es que no estemos usando la última version
_If you have some reason to think you have found a bug in PyInstaller you can try downloading the latest development version.
You can also install the latest version of PyInstaller directly using pip:
pip install -e https://github.com/pyinstaller/pyinstaller/archive/develop.zip_

Otro problema puede ser es que no encuentre automáticamente todos los imports http://pyinstaller.readthedocs.io/en/latest/when-things-go-wrong.html
La solución puede ser hacer un hola mundo, importando un módulo de la manera que dice especificamente que no se debe hacer, ver que genera el ejecutable pero el ejecutable falla, al igual que nos pasa. Investigar como se añaden imports al spec file y probar si podemos arreglar el problema del hola mundo.

**Comment by Itg0001** [comment]
Esta tarea al intentar hacer esto no hemos sido capaces por lo que al ser un lenguaje compilado otra opción es crear una distribución de Python que instale todo lo necesario para su ejecución.

**Comment by joseFranciscoDiez** [comment]
Viendo el github de pyinstaller veo que:
- La versión 3 salió en octubre de 2015 (supuestamente con soporte de python 3.5)
- La versión 3.1 salió en enero de 2016 (con correcciones para el soporte de skimage y pyqt)
- La versión 3.2 salió en mayo de 2016 (con más correcciones para pyqt)

Si de aquí a un mes y poco sale la versión 3.3 con más correcciones para python 3.5, pyqt y windows 10 lo volvemos a probar a ver si hay suerte.

**Comment by Itg0001** [comment]
Correcto, ya vi que si que funciona para otras versiones, no obstante este problema cuando saquen una versión compatible estaría solucionado pero para asegurarnos hemos creado lo que se indicaba a continuación, así que en el peor de los casos hemos conseguido utilizar la distribución que necesitamos únicamente.

Nota: A tener en cuenta que miniconda debe instalarse en C:\Users\NOMBREUSUARIO\Miniconda3
He probado a instalar una maquina virtual e instalarlo allí y el solo al abrir el .bat de ejecutar baja las librerías de las dependencias  y ejecuta la aplicación.

**Comment by joseFranciscoDiez** [comment]
Perfecto. Esto está resuelto con el .bat instalador que descarga las dependencias. Y si diese la casualidad que sacan una versión nueva de pyinstaller lo probamos, sin perder mucho el tiempo, ahora que sabemos que el fallo no es nuestro.
