### ISSUE TITLE
Semana 11: Dudas y problemas con la ejecución

### ISSUE THREAD

**Issue by joseFranciscoDiez** [Itg0001/TFG_DietaPorDientes#53]
1) En el script de ejecución mira a ver si existe una variable miniconda, que pasa si tienes la variable anaconda?

2) En linux se abre, pero al crear un proyecto intenta ejecutar el tesseract.exe y falla. Debería de intentar ejecutar la versión de linux u obviar esa parte y pedir al usuario el valor de la referencia.

**Comment by Itg0001** [comment]
Buenas tardes Jose, no vi la issu y no se porque no se me envían las tuyas al correo en cambio las de Albar
me llegan cada vez que hace algún comentario. Intentare contestar a las preguntas:

1- Hemos echo este paso ya que acordamos que instalar anaconda completo era muy pesado como para mandar al usuario su instalación cerca de 2 Gygas y algo, para ello como requisito es instalar Miniconda el cual en la instalación crea la carpeta Miniconda si tienes aparte instalado anaconda en el mismo ordenador no pasaría nada porque lo primero que hace es añadir Python al principio del path y por lo tanto ese script se ejecutaría desde el Python de miniconda encontrando las rutas perfectamente.

2- Creía que habíamos dicho que solo iba a valer para Windows al usar el Teseract, porque es lo único que nos hace que no sirva desde Linux pero si se puede detectar el tipo de OS  seria añadir esas lineas de código y funcionaria para ambos. 

Un saludo y ya lo miramos mañana en la reunión.

**Comment by Itg0001** [comment]
Por lo que entiendo por el último mensaje que me has mandado, a las chicas las ha funcionado y la parte de que en linux no use Tesseract ha quedado aplicado desde la semana pasada por lo  que esta issue se considerara cerrada ¿no?
