### ISSUE TITLE
Semana 1:  Analizar herramientas de interfaces gráficas y comparativa

### ISSUE THREAD

**Issue by Itg0001** [Itg0001/TFG_DietaPorDientes#6]
Esta primera tarea va a dedicarse a examinar y buscar alternativas para desarrollar mas adelante la interfaz gráfica de la aplicación.

**Comment by Itg0001** [comment]
Buenas tardes he investigado y no podemos pasarlo a pqt5 porque 
anaconda trae instalado por defecto pyqt4 y las funcionalidades de 
muchas librerías como por ejemplo matplotlib entre ellas dejarían de 
funcionar porque aun no están en pyqt de todos modos no es un 
inconveniente porque instalando anaconda ya tendríamos todo lo 
necesario tanto skimage como pyqt y así para el usuario final al que 
está destinado únicamente instalando anaconda ya tendría todo.

He echo la prueba en otro equipo y funciona perfectamente desde línea 
de comando así que es mi equipo el que fallaba lo formateare.

Un saludo.
FDO: Ismael Tobar García

**Comment by alvarag** [comment]
¿Probaste a desinstalar Anaconda e instalar PIP? ¿O no se solucionaba el problema?

**Comment by joseFranciscoDiez** [comment]
Una cosa a tener en cuenta es que va a existir un modo manual o modo de corrección de las lineas calculadas automáticamente, así que quizás poder representar un figure de matplotlib no es tan importante, porque en el otro modo se van a tener que pintar las lineas según los eventos de ratón del usuario.
Ten esto en cuenta. Quizás a la larga es más fácil olvidarse del figure y usar solamente el QPixmap para mostrar las imágenes y las clases de lineas para los trazos. Habría que hacer la conversión entre las coordenadas en la pantalla con las coordenadas que coorresponderían en el QPixmap, esto Sergio Chico lo hizo en el anterior proyecto, se podría adaptar.

**Comment by Itg0001** [comment]
Para obtener las coordenadas del cursor al pulsar el botón  se me ocurrió usar el figure ya que así evitaríamos hacer la correlación del punto (x,y) de la pantalla con el real ya que nos daría el punto (x,y) real de la imagen directamente he implementado un ejemplo de juguete que imprima el pixel de la imagen seleccionado por el ratón y funciona.
