### ISSUE TITLE
Semana 11: Dieta notebook4.ipynb

### ISSUE THREAD

**Issue by joseFranciscoDiez** [Itg0001/TFG_DietaPorDientes#60]
El notebook dieta notebook4.ipynb ocupa 84 megas.

¿Sería posible dividirlo en varios notebooks y que luego un notebook maestro hiciese links a cada una de las divisiones?

Lo digo porque me resulta imposible cargarlo y a cualquier miembro del tribunal que tenga un ordenador tan viejo como el mio le ocurrirá lo mismo.

**Comment by Itg0001** [comment]
Ya esta dividido en 3 notebooks, independientes en cada uno se llevan a cabo una serie de pasos y con run all funcionan todos ellos.
