### ISSUE TITLE
Semana 14: Documentar memorias.

### ISSUE THREAD

**Issue by Itg0001** [Itg0001/TFG_DietaPorDientes#71]
Esta tarea va a consistir en: 

- [ ] corregir los posibles errores o mejorar lo que tenemos subido hasta ahora, añadir nuevas secciones que quedan sin terminar.

**Comment by alvarag** [comment]
Aspectos menores a modificar:

- Tablas con líneas: \toprule, \midrule y \bottomrule.
- Ajustar en las tablas las columnas numéricas a la derecha.
- Poner antes de la primera columna y después de la última: @{}
- El diagrama de casos de uso que se vean más grandes.
- El diagrama de paquetes un poco más pequeño.
- Referenciar anexo 4.
- Figuras E.15 y 16 recortarla.
