### ISSUE TITLE
Semana 14: Documentar anexos.

### ISSUE THREAD

**Issue by Itg0001** [Itg0001/TFG_DietaPorDientes#73]
Esta tarea va a consistir en :

- [ ]  Corregir los posibles errores o mejorar lo que tenemos subido hasta ahora, añadir nuevas secciones que quedan sin terminar en los anexos.

**Comment by alvarag** [comment]
Para la ayuda en línea utilizar:

- La clase de LaTeX: book
- Utilizar un transformador como hlatex u otro para convertir de tex a html

**Comment by alvarag** [comment]
Anexos con comentarios, siguen apareciendo algunas faltas, echa un ojo con el corrector de TexMaker para evitar que se cuele alguna en la versión final.

[anexosC.pdf](https://github.com/Itg0001/TFG_DietaPorDientes/files/660907/anexosC.pdf)

**Comment by alvarag** [comment]
En las tablas de los casos de uso ajusta para evitar que se te vayan de los márgenes

**Comment by Itg0001** [comment]
Ya esta corregido todo lo mencionado.
